name: app_template
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  slang: ^3.28.0
  slang_flutter: ^3.28.0 # dart run slang
  flutter_riverpod: ^2.4.9
  flutter_rust_bridge: 1.82.6
  ffi: ^2.0.1
  window_manager: ^0.3.7

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_rename_app_plus3: ^1.2.3
  flutter_launcher_icons: ^0.13.1

  build_runner_core: ^7.2.9
  ffigen: ^9.0.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0

flutter:
  uses-material-design: true

flutter_rename_app_plus3:
  application_name: App
  dart_package_name: app
  application_id: com.some.app
  bundle_id: com.some.app
  android_package_name: com.some.app
  ios_bundle_name: App

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"